### PR TITLE
Fix to support 4 hex digit colours

### PR DESCRIPTION
**Pull request by david-pfx**
Test program for all colours
Issue #65

### CODE REVIEW

**Comment by Auroriax** [comment]
- I didn't realize that your test project was a PS game. In that case you can add it to the PS+ test cases.
- Your code seems to throw errors on your example project: ` line 94 : Was looking for color for object i, got "8 " instead.
line 94 : Was looking for color for object i, got "8" instead.` I see you only changed the regexes: please double check my comments in #65 for any other code that might need changing.

**Comment by david-pfx** [comment]
The test program is not a test case, it's just a program to run. I still don't know how to turn it into a test case, I just included it for interest.
The test program is supposed to fail on standard PS+ and pass once the PR is applied. Is that what you found?
I did not find any other changes were needed, just the regexes.

**Comment by Auroriax** [comment]
Sorry for the late reply!

Seems like I judged too quickly, and the code does work for object in in your test project. (Not sure what I did wrong but my fault, oops!)

(RE: how to generate tests, in the PS dev readme there are instructions on how to generate tests, but basically, you press Ctrl+J in-editor then follow the instructions there).

I've manually merged this fix and added the colors test to the test cases. So I'll close the PR, but the changes are in PS+.

Thanks!

**Comment by david-pfx** [comment]
No probs. That was just a dry run!
I really feel the need for a better test framework, but for now it'll dew.

**Pull request closed without merging**
